# Generated by Django 5.2 on 2025-04-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='updated_at',
        ),
    ]
